### ISSUE TITLE
Could you show the ServerSide code?

### ISSUE THREAD

**Issue by sajunt4** [Brotherhood94/FlutterWithStripeExample#2]
Hello!

I've been reading your Medium article, and I cannot understand what `postCreatePaymentIntent` method should do.
What should I do in server side? What should I call from Stripe to retrieve that clientSecret?

Thank you!

**Comment by Brotherhood94** [comment]
Hi sajunt4!

Thank you for reading!
This is the [gist](https://gist.github.com/Brotherhood94/2390769b5a0787ef822f3c93b2ac66c3#file-createpaymentintent-py) regarding the server side.
The above code handles the POSTs invoked by the "postCreatePaymentIntent" method defined in the App-Side.
Once the app invokes this function (which encapsulates the POST method), the clientSecret is returned from the server.

Hope it helps! :)

**Comment by jessp01** [comment]
Hi @Brotherhood94,

Very useful indeed, thanks for that.
If anyone is interested in implementing the server side code using Firebase, this worked for me:

```js
const functions = require('firebase-functions');
const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);

const firestore = admin.firestore();
const settings = { timestampInSnapshots: true };
firestore.settings(settings)
// your secret here
const stripe = require('stripe')('sk_test');
exports.createPaymentIntent = functions.https.onRequest((req, res) => { 
    var data = req.body;
    functions.logger.log("Here's a request object:", data);

    return stripe.paymentIntents.create({
        amount: data.amount,
        currency: data.currency,
        payment_method_types: ['card'],
        receipt_email: data.email,
        payment_method: data.payment_method_id,
        confirm: true,
    },   
    {    
      stripeAccount: 'YOUR_ACCOUNT_ID_HERE',
     
    },    function(err, paymentIntent) {
                // asynchronously called
                const paymentIntentReference = paymentIntent;
                if (err !== null){
                    functions.logger.log("Error payment intent:", err);
                    res.send('error');
                } else {
                    console.log('Created paymentintent: ', paymentIntent);
                    functions.logger.log("paymentIntent object:", paymentIntent);
                    res.json({
                        clientSecret: paymentIntent.client_secret,
                    });
                }
    }
  );

});
```

**Comment by Brotherhood94** [comment]
Thank you @jessp01, very useful :)

**Comment by jessp01** [comment]
No worries @Brotherhood94. Happy to submit a pull to update the README if you'd be willing to accept it. I reckon adding both the Python and NodeJS with Firebase examples to it may be beneficial to others.

Cheers,

**Comment by Brotherhood94** [comment]
Great idea! I’ll accept it for sure.

**Comment by jessp01** [comment]
Submitted:) Please see https://github.com/Brotherhood94/FlutterWithStripeExample/pull/5/files

**Comment by Brotherhood94** [comment]
Merged :) Thank you!
